// ---------------------------------------------------------------------------
// Pipeline B — Planner Contract Types
//
// ARCHITECTURE RULE: This file imports from existing domain types only.
// It does NOT duplicate enums, IDs, or shapes already defined elsewhere.
// It is consumed exclusively by Pipeline B — never by Pipeline A.
//
// Import sources allowed:
//   @/types/content     — PlatformV2, Language, MarketingObjectiveV2, GeneratedContent
//   @/lib/evaluation/types — PersonaId
//   @/lib/content/personas/topologyDefinitions — TopologyEdge (reference only)
//
// ---------------------------------------------------------------------------

import type { 
  PlatformV2, 
  Language, 
  MarketingObjectiveV2, 
  GeneratedContent,
  GenerationPurpose,
  CopyFramework,
  MarketingToneId
} from "@/types/content.ts";
import type { PersonaId } from "@/lib/evaluation/types.ts";

// "marketing" is a pseudo-persona drawn from MARKETING_TOPOLOGIES; the IR graph
// routes on the engine purpose, so marketers and thought personas share it.
export type IRPersonaId = PersonaId | "marketing";

// ---------------------------------------------------------------------------
// Request
// ---------------------------------------------------------------------------

export interface PlannerConstraints {
  /** Words/phrases to exclude from the rendered output. Max 10. */
  forbiddenTerms?: string[];
  /** Words/phrases that must appear in the rendered output. Max 10. */
  requiredTerms?: string[];
  /** Maximum character count for the rendered content body. */
  maxLength?: number;
  /** Free-form instructions passed to the renderer. Max 300 chars. */
  customInstructions?: string;
  /**
   * Evaluation-only: forces the renderer into a specific rhetorical mode.
   * Used by the Intellectual Diversity benchmark. Not exposed in production.
   */
  forcedIntellectualMode?: "thought_provoking" | "analytical" | "philosophical";
  /**
   * Evaluation-only: forces compact topology for short-budget platforms (e.g. X).
   * Only applies when persona = "intellectual".
   */
  forcedIntellectualModeVariant?: "standard" | "compact";
}

export interface PlannerRequest {
  /** Must be a persona with a defined topology in TOPOLOGY_REQUIRED. */
  persona: PersonaId;
  /** The content topic. Min 10 chars, max 500 chars. */
  topic: string;
  /** Target publishing platform. Must be a value from PLATFORMS_V2. */
  platform: PlatformV2;
  /** Marketing or content objective. */
  objective: MarketingObjectiveV2;
  /** Output language. */
  language: Language;
  /** Optional audience description. Max 200 chars. */
  audience?: string;
  /** Optional output constraints. */
  constraints?: PlannerConstraints;
  /** Which engine should process. Defaults to "thought" for backward compat. */
  purpose?: GenerationPurpose;
  /** Marketing-specific: tone of voice. */
  tone?: MarketingToneId;
  /** Marketing-specific: copy framework. */
  copyFramework?: CopyFramework;
  /** Marketing-specific: The core message to convey. */
  keyMessage?: string;
}

/**
 * The strictly validated internal request representation.
 * Impossible states (like marketing + persona) are stripped out.
 */
export interface NormalizedPlannerRequest {
  topic: string;
  platform: PlatformV2;
  objective: MarketingObjectiveV2;
  language: Language;
  audience?: string;
  constraints?: PlannerConstraints;
  
  // REQUIRED internally
  purpose: GenerationPurpose;
  useLegacyEngine?: boolean;
  
  // Thought ONLY
  persona?: PersonaId;
  
  // Marketing ONLY
  tone?: MarketingToneId;
  copyFramework?: CopyFramework;
  keyMessage?: string;
}

// ---------------------------------------------------------------------------
// Intermediate Representation (IR)
// ---------------------------------------------------------------------------

/**
 * A single semantic node in the IR graph.
 *
 * The `id` MUST correspond to a node name in TOPOLOGY_REQUIRED[personaId].nodes.
 * Any node id outside that set is a forbidden-node violation.
 */
export interface IRNode {
  /** Matches TOPOLOGY_REQUIRED[persona].nodes[i] exactly. */
  id: string;
  /** Semantic content generated by the planner for this node. Must not be empty. */
  content: string;
  /**
   * Optional planner confidence for this node's content (0–1).
   * Used for observability and async evaluation only — not exposed to end users.
   */
  confidence?: number;
}

/**
 * A directed edge between two IR nodes.
 *
 * Edges are compiled deterministically from TOPOLOGY_REQUIRED — the planner
 * does NOT generate edges. They are injected by the IR compiler after planning.
 */
export interface IREdge {
  from: string;
  to: string;
  /** Relation label, must match TOPOLOGY_REQUIRED[persona].edges[i].rel. */
  rel: string;
}

/**
 * The complete Intermediate Representation graph for one planning run.
 *
 * Invariants (enforced by validateIRGraph):
 *   - nodes map 1-to-1 with TOPOLOGY_REQUIRED[personaId].nodes (no extra, no missing)
 *   - edges mirror TOPOLOGY_REQUIRED[personaId].edges exactly
 *   - no duplicate node ids
 *   - no duplicate edges (from+to pair)
 *   - all node.content non-empty
 *   - confidence, when present, is in [0, 1]
 */
export interface IRGraph {
  personaId: IRPersonaId;
  nodes: IRNode[];
  edges: IREdge[];
  /** Schema version — bump when IRGraph shape changes: "major.minor.patch" */
  version: string;
}

export interface IRAngle {
  type: string;
  priority: "high" | "medium" | "low";
  content: string;
  /** IDs of the nodes from the IR graph that factually support this angle. */
  sourceNodes: string[];
}

export interface MarketingIRGraph extends IRGraph {
  angles: IRAngle[];
}

// ---------------------------------------------------------------------------
// Response
// ---------------------------------------------------------------------------

export interface TokenUsage {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  thoughtsTokens?: number;
}

export interface PlannerMetadata {
  personaId: PersonaId;
  platform: PlatformV2;
  /** Model used for the planning step. */
  plannerModel: string;
  /** Model used for the rendering step. */
  rendererModel: string;
  /** Latency of the planner LLM call only. */
  plannerLatencyMs: number;
  /** Latency of the renderer LLM call only. */
  rendererLatencyMs: number;
  /** plannerLatencyMs + rendererLatencyMs + overhead. */
  totalLatencyMs: number;
  plannerTokens?: TokenUsage;
  rendererTokens?: TokenUsage;
  /** IR schema version in use. */
  irVersion: string;
  /** Pipeline B version — "B-major.minor.patch" */
  pipelineVersion: string;
  requestId: string;
  timestamp: string;
}

/**
 * Successful response from Pipeline B.
 *
 * renderedContent uses the same GeneratedContent shape as Pipeline A —
 * intentionally, to make A/B comparison structurally trivial.
 * Any extensions to the output shape must come AFTER quality is proven.
 */
export interface PlannerResponse {
  success: true;
  requestId: string;
  ir: IRGraph;
  /** Final rendered output. Same shape as Pipeline A GeneratedContent. */
  renderedContent: GeneratedContent;
  metadata: PlannerMetadata;
}

/**
 * Failed response from Pipeline B.
 *
 * userMessage is safe to display. Internal diagnostic details
 * are logged server-side only — never included in this object.
 */
export interface PlannerErrorResponse {
  success: false;
  requestId: string;
  error: {
    code: string;
    /** Arabic-language safe message for the end user. */
    userMessage: string;
    /** Whether this error is safe to surface to the end user. */
    isUserFacing: boolean;
  };
}

export type PlannerResult = PlannerResponse | PlannerErrorResponse;
